version: '3'
services:
  agar-io-cigar:
    build:
      args:
        OGAR_SERVER: "HOSTNAME_AND_PORT"
  tetris-red-tetris:
    build:
      args:
        RED_TETRIS_SERVER: "HOSTNAME_AND_PORT"
  tetris-teturisu-client:
    build:
      args:
        TETURISU_SERVER: "HOSTNAME_AND_PORT"
  tetris-battletris:
    build:
      args:
        BATTLETRIS_SERVER: "HOSTNAME_AND_PORT"
